apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP #This means that the IP assigned to this service is only accesible from inside the cluster
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

